### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by vitornogueira** [fisioeng/fisioeng-webapp#1]
An error occurred while installing mysql2 (0.3.18), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.18'` succeeds before bundling.

**Comment by dayvsonlima** [comment]
you tried to run gem install mysql2 -v '0.3.18' in its rvm with the 2.0.0 version of ruby and 4 or greater rails? @vitornogueira

**Comment by joseronierison** [comment]
Vitor, try to install <tt> sudo apt-get install libmysql-ruby libmysqlclient-dev </tt>, after run bundle install again. @vitornogueira

**Comment by vitornogueira** [comment]
Thanks @dayvsonlima and @Ronierison. I found this [link](http://stackoverflow.com/a/19765422/2631745) and solved the problem.

```
sudo apt-get install mysql-client libmysqlclient-dev
```

:+1:  :smiley:

**Comment by dayvsonlima** [comment]
@Ronierison would be nice to add this wiki
